---
# handlers file for hswong3i.gluster

- name: restart gluster
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "glusterfs-server", state: "restarted" }
